# Generated by Django 2.2.4 on 2019-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='codigo',
            field=models.CharField(default='test', max_length=15, verbose_name='Codigo de Habitacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='descripcion',
            field=models.TextField(max_length=400, verbose_name='Descripcion del Cuarto'),
        ),
        migrations.AlterField(
            model_name='room',
            name='path_image',
            field=models.CharField(max_length=500, verbose_name='Url de la imagen'),
        ),
    ]
