# Generated by Django 2.2.4 on 2019-10-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='path_image',
            field=models.CharField(default='url test', max_length=200, verbose_name='Url de la imagen'),
            preserve_default=False,
        ),
    ]
