# Generated by Django 2.2.4 on 2019-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='path_image',
            field=models.FileField(max_length=250, upload_to='documents/', verbose_name='Subir Imagen'),
        ),
    ]
