# Generated by Django 2.2.4 on 2019-09-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.BookingType'),
        ),
    ]
