# Generated by Django 2.2.4 on 2019-10-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='calificacion',
            field=models.IntegerField(default=0, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='room',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion del Cuarto'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id_roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.RoomType', verbose_name='Tipo de Cuarto'),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_adultos',
            field=models.IntegerField(default=0, verbose_name='Numero de Adultos'),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_camas',
            field=models.IntegerField(default=0, verbose_name='Numero de Camas'),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_ninos',
            field=models.IntegerField(default=0, verbose_name='Numero de Niños'),
        ),
        migrations.AlterField(
            model_name='room',
            name='path_image',
            field=models.TextField(null=True, verbose_name='Url de Imagen'),
        ),
        migrations.AlterField(
            model_name='room',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
