# Generated by Django 2.2.4 on 2019-09-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='eliminado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
