# Generated by Django 2.2.4 on 2019-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bookingtype_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_ninos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
