# Generated by Django 2.2.6 on 2019-10-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fecha_ingresado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
