# Generated by Django 2.2.4 on 2019-09-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20190906_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
