# Generated by Django 2.2.4 on 2019-10-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20191004_1331'),
        ('reservas', '0002_auto_20191001_1855'),
    ]

    operations = [
    ]
