# Generated by Django 2.2.4 on 2019-12-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20191203_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='precio',
            new_name='total_to_pay',
        ),
    ]
