# Generated by Django 2.2.4 on 2019-11-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20191101_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='descripcion',
            field=models.TextField(max_length=300, verbose_name='Descripcion del Cuarto'),
        ),
    ]
