# Generated by Django 2.2.4 on 2019-11-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='path_image',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
