# Generated by Django 2.2.4 on 2019-10-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20191028_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='path_image',
            field=models.CharField(max_length=500, verbose_name='Url de la imagen'),
        ),
    ]
