# Generated by Django 2.2.4 on 2019-12-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20191204_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('details_reason', models.TextField()),
                ('amount', models.FloatField(default=0)),
                ('is_canceled', models.BooleanField(default=False)),
                ('details_canceled', models.TextField()),
                ('is_removed', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Booking')),
            ],
        ),
    ]
