# Generated by Django 2.2.4 on 2019-09-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20190906_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='num_ninos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_camas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
