# Generated by Django 2.2.4 on 2019-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20190907_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='path_image',
            field=models.TextField(null=True),
        ),
    ]
