# Generated by Django 2.2.4 on 2019-11-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='doc_type',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte'), ('OTROS', 'Otro')], default='Cedula', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
