# Generated by Django 2.2.4 on 2019-09-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0001_initial'),
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tour_packages',
            field=models.ManyToManyField(to='tour_package.Tour_Package'),
        ),
    ]
