# Generated by Django 2.2.4 on 2019-09-10 06:03

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usr',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
