# Generated by Django 2.2.4 on 2019-11-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Documento de Identificación'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='date_birth',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='doc_type',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte'), ('OTROS', 'Otro')], max_length=9, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de Teléfono'),
        ),
    ]
