# Generated by Django 2.2.4 on 2019-11-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_auto_20191108_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
