# Generated by Django 2.2.4 on 2019-10-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_auto_20191024_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
