# Generated by Django 2.2.4 on 2019-09-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_auto_20190910_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
