# Generated by Django 2.2.4 on 2019-08-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_cliente_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
