# Generated by Django 2.2.4 on 2019-08-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_auto_20190811_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
