# Generated by Django 2.2.4 on 2019-11-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_perfil_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='doc_type',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte'), ('OTROS', 'Otro')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
