# Generated by Django 2.2.4 on 2019-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_auto_20190811_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
