# Generated by Django 2.2.7 on 2019-12-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('available_stock', models.IntegerField(default=30)),
                ('company', models.CharField(max_length=120)),
                ('days', models.CharField(max_length=150)),
                ('hours', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('path_image', models.FileField(max_length=250, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_Order',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopping_cart.Product')),
                ('reservation_name', models.CharField(max_length=100)),
                ('tour', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour_package.Tour_Package')),
            ],
            bases=('shopping_cart.product',),
        ),
    ]
