# Generated by Django 2.2.4 on 2019-10-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('path_image', models.CharField(max_length=250)),
            ],
        ),
    ]
