# Generated by Django 2.2.4 on 2019-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_package',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tour_package',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='tour_package',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tour_package',
            name='path_image',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
