# Generated by Django 2.2.4 on 2019-11-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_package',
            name='company',
            field=models.CharField(default='Compania  Test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour_package',
            name='days',
            field=models.CharField(default='Lunes-Miercoles', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour_package',
            name='hours',
            field=models.CharField(default='10am a 12pm', max_length=100),
            preserve_default=False,
        ),
    ]
