# Generated by Django 2.2.7 on 2019-12-02 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0002_auto_20191202_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourorder',
            name='reservation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.Perfil'),
        ),
        migrations.AlterField(
            model_name='tourorder',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour_package.Tour_Package'),
        ),
    ]
