# Generated by Django 2.2.7 on 2019-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0003_auto_20191202_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='available_stock',
            field=models.IntegerField(default=30, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='company',
            field=models.CharField(max_length=120, verbose_name='Compania'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='days',
            field=models.CharField(max_length=150, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripcion del Paquete'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='hours',
            field=models.CharField(max_length=100, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='path_image',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Url de Imagen'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo del Paquete'),
        ),
    ]
